run:
  timeout: 5m
  modules-download-mode: readonly
  allow-parallel-runners: true

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
    - copyloopvar

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/FreePeak/db-mcp-server
  govet:
  revive:
    rules:
      - name: var-naming
        severity: warning
        disabled: false
      - name: exported
        severity: warning
        disabled: false

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
    - vendor/
  exclude:
    - "exported \\w+ (\\S*['.]*)([a-zA-Z'.*]*) should have comment or be unexported" 