version: '3.8'

services:
  mysql1:
    image: mysql:8.0
    container_name: mcp_mysql1
    environment:
      MYSQL_ROOT_PASSWORD: password1
      MYSQL_DATABASE: db1
      MYSQL_USER: user1
      MYSQL_PASSWORD: password1
    ports:
      - "13306:3306"
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user1", "-ppassword1"]
      interval: 5s
      timeout: 5s
      retries: 5

  mysql2:
    image: mysql:8.0
    container_name: mcp_mysql2
    environment:
      MYSQL_ROOT_PASSWORD: password3
      MYSQL_DATABASE: db3
      MYSQL_USER: user3
      MYSQL_PASSWORD: password3
    ports:
      - "13307:3306"
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user3", "-ppassword3"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres1:
    image: postgres:15
    container_name: mcp_postgres1
    environment:
      POSTGRES_USER: user2
      POSTGRES_PASSWORD: password2
      POSTGRES_DB: db2
    ports:
      - "15432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user2 -d db2"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Optional: Add database management tools
  adminer:
    image: adminer:latest
    container_name: mcp_adminer
    ports:
      - "18080:8080"
    depends_on:
      - mysql1
      - mysql2
      - postgres1

networks:
  default:
    name: mcp_test_network 