version: '3.8'

services:
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    environment:
      - SERVER_PORT=9090
      - TRANSPORT_MODE=sse
      - DB_TYPE=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=mcp_user
      - DB_PASSWORD=mcp_password
      - DB_NAME=mcp_db
      - LOG_LEVEL=info
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=mcp_db
      - MYSQL_USER=mcp_user
      - MYSQL_PASSWORD=mcp_password
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data: 