version: '3'

services:
  db-mcp-server:
    build: .
    ports:
      - "9092:9092"
    environment:
      - SERVER_PORT=9092
      - TRANSPORT_MODE=sse
      - DB_CONFIG_FILE=/app/config.json
      - MCP_TOOL_PREFIX=mcp_cashflow_db_mcp_server_sse
    volumes:
      - ./config.json:/app/config.json
      - ./.env:/app/.env
    depends_on:
      - mysql1
      - mysql2

  mysql1:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db1
      MYSQL_USER: user1
      MYSQL_PASSWORD: password1
    ports:
      - "13306:3306"
    volumes:
      - mysql1_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  mysql2:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db2
      MYSQL_USER: user2
      MYSQL_PASSWORD: password2
    ports:
      - "13307:3306"
    volumes:
      - mysql2_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql1_data:
  mysql2_data: 